
services:
  staging_db:
    image: postgres:latest
    hostname: staging_bank_marketing
    container_name: staging_bank_marketing_container
    restart: on-failure
    environment:
      POSTGRES_DB: ${DB_STG_BANK}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./marketing_staging/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${PORT_STAGING}:5432"
    networks:
      - my_network

  warehouse_db:
    image: postgres:latest
    hostname: warehouse_bank_marketing
    container_name: warehouse_bank_marketing_container
    restart: on-failure
    environment:
      POSTGRES_DB: ${DB_WH_BANK}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./marketing_warehouse/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${PORT_WAREHOUSE}:5432"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
